### ISSUE TITLE
Globally disable Elvish Sylph advancement from Elvish Enchantress

### ISSUE THREAD

**Issue by shikadilord** [shikadilord/Invasion_from_the_Unknown#6]
The mainline Elvish Sylphs are extremely over-powered for long-running campaigns such as this one. I had disabled them temporarily before by using a separate Elvish Shaman clone line with identical stats and WML, but nowadays it should be possible to use global events to override unit XP and advances_to attributes when leveling up Sorceress to Enchantress.

This is a major balancing issue and thus blocks 2.0.0.

**Comment by Konrad22** [comment]
Would you mind adding the information that the Enchantress can't level up to a Sylph in the first or second scenario? Somewhere very early.
I can imagine that it would be almost heartbreaking to notice this only after leveling up a Sorceress.
